### ISSUE TITLE
Asset compiler problems

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#108]

**Comment by joeljunstrom** [comment]
Is this that heroku doesnt precompile the assets when comoiling the slug?

**Comment by lexi** [comment]
Yes, and that it takes a couple of minutes for the assets to be accessible after manual compile.

**Comment by arvida** [comment]
https://github.com/rumblelabs/asset_sync/issues/5#issuecomment-1961698

**Comment by arvida** [comment]
Now its done when pushing to heroku.. Fixed in unicef project commit #7537a48298262334ba118f50aabe162673729ba7

**Comment by joeljunstrom** [comment]
:+1:
