### ISSUE TITLE
Make admin interface responsive

### ISSUE THREAD

**Issue by joeljunstrom** [oktavilla/Porthos-Engine#115]

**Comment by lexi** [comment]
huh?

**Comment by joeljunstrom** [comment]
ehhh

**Comment by joeljunstrom** [comment]
for the lulz?

**Comment by lexi** [comment]
ah, 3.1...

**Comment by joeljunstrom** [comment]
heh it was @arvida that openet it, on my comp, due to things looking mighty WRONG! if you resize. (it's not really "responsive" but rather the wrong column gets resized)
