### ISSUE TITLE
link in navigation_links needs to take a class

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#148]
I would like to be able to set a class (or maybe any html attr) for `link` in `navigation_links`.

https://github.com/Oktavilla/Porthos-Engine/blob/master/app/helpers/link_lists_helper.rb#L7-l16

So I can do:

```
<% navigation_links(LinkList['our_work']).each do |link| %>
  <li><%= link, class: 'nav-item' %></li>
<% end %>
```

If that `link` is current it should also get `.current`

ping @joeljunstrom @arvida

**Comment by joeljunstrom** [comment]
This should probably be removed from porthos. We added the helper to the client project instead.
