### ISSUE TITLE
Resizor features

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#16]
- Crop view so we can link there to resize images in specified format.
- Being able to use your own S3 bucket
- Check if it converts CMYK images

**Comment by arvida** [comment]
Vid migrering
- Verkar som det funkar att ge IAM använder access till andra användares buckets, behöver skapa nytt aws konto för resizor
- Byta source för cdn.resizor.com
- Radera versions / Flytta till shared bucket

**Comment by arvida** [comment]
Uppdatera dokumentation

**Comment by arvida** [comment]
Har flyttat unicefs bilder till deras s3 konto nu
Har gjort så bilder automatiskt konverteras till rgb när de skalas om
Det går att kroppa bilder med c200x100-45x20 (c[width]x[height]-[x]x[y])

**Comment by lexi** [comment]
Jävligt fett!
Lite buggigt huruvida den laddar jcrop, får ladda om ett gäng gånger för att den ska laddas. Verkar vara när man har sparat en cropping, eller så är det när bilden man har som underlag för att croppa är cachad.
Den verkar inte heller uppdatera bilden med den nya beskärningen, kanske har med Cloudfront att göra?
Bara testat lokalt.

**Comment by arvida** [comment]
Jo, det är något skumt med js där, verkar inte funka alla gånger sidan laddas..

Testa att uppdatera resizor gemen, är nog det som gör att den inte använder den nya rendereringen.
