### ISSUE TITLE
Det verkar vara nåt knas med nåt regexp

### ISSUE THREAD

**Issue by martinlissmyr** [oktavilla/Porthos-Engine#2]
felmeddelande: "/Library/Ruby/Gems/1.8/bundler/gems/Porthos-Engine-0af7c2faec15/lib/porthos/routing.rb:55: invalid regular expression; there's no previous pattern, to which '{' would define cardinality at 1: /{{(\w+)}}/"

:)

**Comment by joeljunstrom** [comment]
Ah tror det är en skillnad i ruby 1.8.7 och 1.9.2
Har du satt upp rvm hemma? I så fall; rvm install 1.9.2; rvm use 1.9.2 och testa igen

**Comment by martinlissmyr** [comment]
Får testa ikväll. Danke. 

/martin

Martin Lissmyr
Oktavilla
070-794 35 75

**Comment by martinlissmyr** [comment]
Det funkar nu... finfint :)
