### ISSUE TITLE
Link lists

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#25]
- A list with links
- Has a handle to use in the templates
- It's sorted
- Every link has a name and a relation to a resource (model and possibly an id) or just an url
- The link should know if it is current

**Comment by joeljunstrom** [comment]
Partly resolved by 4507f22d4cd8aaa7bbdd72cea7fe3bcba77237a9 and 768fe88d71a39a97d1b7877f436d94057d6a987a
I forgot to use --no-ff so two commits :zzz:

**Comment by joeljunstrom** [comment]
Superseded by #47
