### ISSUE TITLE
Switching which user I'm logged in as

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#54]
During some scenario the user I'm logged in as is switched. For example, now I was logged in as myself and after a while I'm suddenly logged in as karolina. Not too great =)

I think it might happen when I created a page. It happened once yesterday too.

**Comment by lexi** [comment]
Seems it happens when multiple users are logged in at the same time. Tried being logged in as me in Chrome and joel in Firefox. Both became logged in as same user. When I logged out both became logged out.

Cool feature =)

**Comment by joeljunstrom** [comment]
Måste vara att man delar sessionid på nått vänster?

**Comment by arvida** [comment]
Lite info här: https://github.com/mperham/dalli/issues/101
Men det verkar inte funka bättre med HEAD..

**Comment by arvida** [comment]
Har [commitat](https://github.com/winstondesign/UNICEF/commit/4f927cdf870e61d2f7bb70b6f5c0767b2f0c1859) temp fix i Unicef
