### ISSUE TITLE
propagate custom templates does not work, dies

### ISSUE THREAD

**Issue by joeljunstrom** [oktavilla/Porthos-Engine#63]

**Comment by joeljunstrom** [comment]
Cant seem to reproduce this locally, anyone else?

**Comment by lexi** [comment]
What should I test?

**Comment by joeljunstrom** [comment]
This should be resolved after 821b8e3dc902879c9c94bd73085fe950dff01037 as long as we run the migration script added in d3a9d603bda5de4445db38423282451f2d97a8ac

**Comment by lexi** [comment]
Deployed?

**Comment by joeljunstrom** [comment]
YA
