### ISSUE TITLE
Link datum_template

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#66]
A link datum template should contain:
- Linktext
- Relation to a page (be able to choose which page_templates)
- ... or a uri

Relation / uri should be exclusive.

**Comment by joeljunstrom** [comment]
Closed by 346dbeaa1739bc45b8298d7e4537e87dfbe69bfd

**Comment by joeljunstrom** [comment]
Unfortunately it doesnt really work
