### ISSUE TITLE
Changing handle on a datum_template breaks

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#74]
Changing handle on a datum_template on a template breaks all existing pages with that template.

Make the field inactive awaiting a proper fix?

**Comment by joeljunstrom** [comment]
Do you mean it's a bug or that the template breaks? If it's a bug it's a regression

**Comment by lexi** [comment]
That the template would break is obvious =)

All existing pages admin view with that template breaks.

**Comment by lexi** [comment]
Btw, what's a regression?

**Comment by joeljunstrom** [comment]
A fixed bug that comes back with a vengance

**Comment by lexi** [comment]
Ahh, guess you need a regression test then! =)
