### ISSUE TITLE
MultiJson::DecodeError when deleting resizor asset

### ISSUE THREAD

**Issue by arvida** [oktavilla/Porthos-Engine#86]

**Comment by joeljunstrom** [comment]
It was an discussion on rails issues recently but I canny find it now, if I remember it correctly render :head returns a body consisting of a space " ". Dunno why but probably to avoid some issue in some browser, they were talking about fixing it by returning a {} instead, but don't think it's gonna get in soon enough...

**Comment by joeljunstrom** [comment]
oh here https://github.com/rails/rails/issues/1742

**Comment by arvida** [comment]
Done in resizor rep.
