### ISSUE TITLE
AssetAssociations should be able to have local changes

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#87]
When you add an asset_association you should be able to edit the description (and possibly title) for the asset in that context while remaining the association to the original. You should also be able to "reset" to the original value.

**Comment by lexi** [comment]
I think this one is quite important for Unicef. They've asked for it a couple of times. Is it very difficult? ;)

**Comment by joeljunstrom** [comment]
You should also be able to "reset" to the original value.
