### ISSUE TITLE
Display options for asset_associations

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#88]
Being able to choose display options for asset_associations. Size and alignment (left, right) are the ones I can think of now.

Choose alignment:

[x]  Full / center
[  ]  Right
[  ]  Left

Choose size:

[x]  Fullwidth (575 px)
[  ]  Medium (320 px)
[  ]  Small (150 px)

Would be usefull if they could be shared across templates but also set specifically for one. But that might be a big hazzle.

**Comment by lexi** [comment]
Maybe display_options could be useful on other datums too.

**Comment by joeljunstrom** [comment]
FIXME: touch chains for items with data pointing to display options. Display options must store references to it's uses.
FIXME: How does deleting a display option affect items.

**Comment by joeljunstrom** [comment]
FIXME: persisted association ids should ve stored as a set

**Comment by joeljunstrom** [comment]
Resolved by #141
